name: Automatically update Folia commit hash

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Mint repository
        uses: actions/checkout@v4
        with:
          path: 'Mint'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Folia repository
        uses: actions/checkout@v4
        with:
          path: 'Folia'
          repository: "PaperMC/Folia"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Folia latest commit Hash
        id: foliaRef
        run: |
          cd Folia
          echo "NEW_FOLIA_REF=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Get Mint Current Folia commit Hash
        id: currFoliaRef
        run: |
          cd Mint
          OLD_FOLIA_REF=$(grep "^foliaRef\s*=" gradle.properties | sed 's/^foliaRef\s*=\s*//')
          echo "OLD_FOLIA_REF=$OLD_FOLIA_REF" >> $GITHUB_OUTPUT

      - name: Update foliaRef in Mint
        run: |
          cd Mint
          if [ -n "$NEW_FOLIA_REF" ]; then
            sed -i "s/\(foliaRef\s*=\s*\).*/\1$NEW_FOLIA_REF/" gradle.properties
          else
            echo "NEW_FOLIA_REF is empty — skipping update to gradle.properties"
            exit 1
          fi
        env:
          NEW_FOLIA_REF: ${{ steps.foliaRef.outputs.NEW_FOLIA_REF }}

      - name: Grant execute permission for gradlew
        run: |
          cd Mint
          git config --global user.name "Bacteriawa"
          git config --global user.email A3167717663@hotmail.com
          chmod +x gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Running tests before push
        run: |
          cd Mint
          if ! git diff --quiet; then
            echo "Running tests...."
            ./gradlew applyAllPatches
            ./gradlew build -x test
            ./gradlew rebuildPaperApiPatches
            ./gradlew rebuildAllServerPatches
          fi

      - name: Check for changes and write to repository
        run: |
          cd Mint
          if ! git diff --quiet; then
            echo "Writing to repo....."
            git add .
            chmod +x ./scripts/Upstream.sh
            ./scripts/Upstream.sh --paper $OLD_FOLIA_REF
            git push
          else
            echo "No changes to commit."
          fi
        env:
          OLD_FOLIA_REF: ${{ steps.currFoliaRef.outputs.OLD_FOLIA_REF }}
